// lib/data.js

export const experience = [
  {
    dates: '05.2025 – 08.2025',
    title: 'Software Architect Intern',
    company: 'Solita Oy',
    points: [
      'Contributed to the architectural design of a pothole detection system integrating mobile sensors and cloud infrastructure',
      'Designed scalable AWS backend architecture using Lambda, API Gateway, DynamoDB, and S3 for real-time data processing',
      'Planned sensor fusion integration to enhance motion detection reliability from mobile data sources',
      'Designed data flow for real-time GPS tagging and geolocation-based event recording',
      'Created specifications for a web-based dashboard to visualize pothole data for road maintenance teams',
      'Collaborated with mobile developers and data engineers to align architectural goals with technical constraints',
      'Documented system architecture and produced internal diagrams for deployment and knowledge sharing',
      'Participated in internal technical reviews and contributed to roadmap planning',
    ],
  },
  {
    dates: '05.2024 – 08.2024',
    title: 'FullStack Developer',
    company: 'Casamedia',
    points: [
      'Developed responsive UI using Flutter widgets',
      'Integrated RESTful APIs for real-time data',
      'Ensured performance optimization for iOS and Android',
      'Implemented secure storage for sensitive data',
      'Used Flutter plugins for GPS, Camera, and Local Storage',
      'Conducted unit and integration testing',
      'Deployed backend with Node.js and Express.js',
      'Managed databases using MongoDB and Firebase Firestore',
      'Built CI/CD pipelines with GitHub Actions',
      'Collaborated with teams to ship new features and participated in code reviews',
      'Maintained codebase and API documentation',
    ],
  },
  {
    dates: '01.2024 – 04.2024',
    title: 'Project Manager',
    company: 'Tampere University of Applied Sciences',
    points: [
      'Led a RaspberryPi-based network to manage 3D printers',
      'Managed team tasks using Jira, Confluence, and Git',
      'Set up and maintained a Flask server for printer operations',
      'Created MySQL databases; implemented AutoSSH and SSH tunneling',
      'Deployed cloud infrastructure for remote monitoring and management',
      'Automated routine tasks to enhance system efficiency',
      'Ensured data security via encrypted connections and secure authentication',
      'Conducted team training on tools and technologies',
      'Documented project progress and created a comprehensive project report',
      'Presented project outcomes to faculty and peers',
    ],
  },
  {
    dates: '10.2018 – 03.2019',
    title: 'Market Research Analyst Intern',
    company: 'Kajaani University of Applied Sciences',
    points: [
      'Conducted international market research and collected relevant data',
      'Contributed to project planning and evaluated risk factors',
      'Performed data analysis to support decision-making',
      'Assisted in preparing documentation and reports',
      'Developed and executed marketing plans',
      'Supported product development and pricing strategies',
      'Prepared and delivered frequent presentations',
      'Maintained customer relationships and handled client communications',
    ],
  },
];

export const education = [
  {
    dates: '2025 – 2027',
    degree: "Master's Degree in Computer Sciences",
    school: 'University of Helsinki',
    details: [
      'Major: Algorithms',
      'Neural Networks and Deep Learning',
      'Advanced Machine Learning',
      'Advanced Bayesian Inference',
      'Computational Statistics',
      'Algorithms in Genome Analysis',
      'Computational Methods',
      'Computer Vision',
      'Introduction to Data Science',
      'String Processing Algorithms',
      'Bayesian Data Analysis',
      'Software Testing',
      'Interactive Data Visualization',
      'Software Architecture',
      'Programming Parallel Computers',
      'Transaction Management and Query Optimization',
      'Human Computer Interaction',
    ],
  },
  {
    dates: '2021 – 2025',
    degree: 'Bachelor of Engineering',
    school: 'Tampere University of Applied Sciences',
    details: [
      'Major: Software Engineering',
      'Grade: 4.50 / 5',
      'Programming Languages (C++, Java, JavaScript, Python etc.)',
      'Embedded Systems, IoT',
      'Web & Mobile App Development (Frontend, Backend, HTML, Node.js, React, React Native, APIs)',
      'DevOps (Docker, CI/CD, Automation)',
      'User Interfaces, Usability and UX (Qt)',
      'Software Automation (Robot Framework, Cucumber), Unit Testing (JUnit)',
      'Software Architectures and Engineering',
      'Data Analytics, Machine Learning and Deep Learning (SQL, PostgreSQL, Tableau, Matlab, Matplotlib, NumPy, Pandas, Reinforcement Learning, CNN, ANN, NLP, Decision Tree, Random Forest, AutoML, Neural Network Architecture etc.)',
      'Software Projects',
    ],
  },
];
